# Generated by Django 4.2.5 on 2023-11-16 21:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Brand Name')),
                ('company_legal_name', models.CharField(max_length=200, verbose_name='Company Legal Name')),
                ('company_number', models.CharField(max_length=200, verbose_name='Company Number')),
                ('address_line_1', models.CharField(blank=True, max_length=200, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('postcode', models.CharField(blank=True, max_length=50, verbose_name='Postcode')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Creation Time (UTC)')),
                ('bike_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Bike Commission (%)')),
                ('accessories_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Accessories Commission (%)')),
                ('clothing_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Clothing Commission (%)')),
                ('maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Maintenance (%)')),
                ('bike_parts', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Bike Parts (%)')),
                ('pre_owned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pre-owned (%)')),
                ('logo', models.ImageField(upload_to='vendor/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='VendorShopConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=200, verbose_name='Your shop URL')),
                ('access_token', models.CharField(max_length=100, verbose_name='API Access Token')),
                ('api_key', models.CharField(max_length=100, verbose_name='API Key')),
                ('api_secret_key', models.CharField(max_length=100, verbose_name='API Secret Key')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_connection', to='vendors.vendor')),
            ],
        ),
    ]
