# Generated by Django 4.2.5 on 2023-12-12 22:45

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_background_image_category_heading_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='accessories_commission',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bike_commission',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bike_parts',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='clothing_commission',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='pre_owned',
        ),
        migrations.CreateModel(
            name='VendorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Commission (%)')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='categories.subcategory', verbose_name='Nested Category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='vendors.vendor', verbose_name='Vendor')),
            ],
        ),
    ]
