# Generated by Django 4.2.5 on 2023-12-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendorcommission_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorshopconnection',
            name='api_key',
            field=models.CharField(max_length=100, null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='vendorshopconnection',
            name='api_secret_key',
            field=models.CharField(max_length=100, null=True, verbose_name='API Secret Key'),
        ),
        migrations.AlterField(
            model_name='vendorshopconnection',
            name='shop_url',
            field=models.CharField(max_length=200, unique=True, verbose_name='Your shop URL'),
        ),
    ]
