# Generated by Django 4.2.5 on 2023-12-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendorshopconnection_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorcommission',
            name='value',
        ),
    ]
