# Generated by Django 4.2.5 on 2024-02-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_vendor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorshopconnection',
            name='is_shop_valid',
            field=models.BooleanField(default=True, verbose_name='Is shop valid'),
        ),
    ]
