# Generated by Django 4.2.5 on 2024-04-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0008_vendorshopconnection_is_shop_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="vat_number",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="VAT Number"),
        ),
    ]
