# Generated by Django 4.2.5 on 2024-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0009_vendor_vat_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorshopconnection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
