# Generated by Django 4.2.5 on 2024-08-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendorshopconnection_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_send_receipt',
            field=models.BooleanField(default=True, verbose_name='Send Receipt'),
        ),
    ]
